 export const GET_NAME_REQUEST ="GET_NAME_REQUEST"
 export const GET_NAME_SUCCESS ="GET_NAME_SUCCESS"
 export const GET_NAME_FAILURE ="GET_NAME_FAILURE"



 export const GET_WORD_REQUEST ="GET_WORD_REQUEST"
 export const GET_WORD_SUCCESS ="GET_WORD_SUCCESS"
 export const GET_WORD_FAILURE ="GET_WORD_FAILURE"



 export const GET_SCORE_REQUEST ="GET_SCORE_REQUEST"
 export const GET_SCORE_SUCCESS ="GET_SCORE_SUCCESS"
 export const GET_SCORE_FAILURE ="GET_SCORE_FAILURE"


 export const GET_LEVEL_REQUEST ="GET_LEVEL_REQUEST"
 export const GET_LEVEL_SUCCESS ="GET_LEVEL_SUCCESS"
 export const GET_LEVEL_FAILURE ="GET_LEVEL_FAILURE"


